# name or the intended use of these models
name: 'Sun_youth_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'Sun_youth_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  Sun_youth_dbt:  
    staging:
      +schema: l2_PROCESSING
      +materialized: view
    marts:
      +schema: l3_CONSUMPTION
      +materialized: table